// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0uzLJyIiNG3JCSF8J0M4LYPjd2FILMOo',
    appId: '1:568613442085:web:757ea28f98dfeb3054e5cc',
    messagingSenderId: '568613442085',
    projectId: 'task-sphere-e46ad',
    authDomain: 'task-sphere-e46ad.firebaseapp.com',
    storageBucket: 'task-sphere-e46ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGCalr6KvjKP-6x8lCt7hdnRc8A6NQLl8',
    appId: '1:568613442085:android:302387b7708efef054e5cc',
    messagingSenderId: '568613442085',
    projectId: 'task-sphere-e46ad',
    storageBucket: 'task-sphere-e46ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQj7dXWQ0bdEKoz5kZ4Z0mnkiwKWB1Xw',
    appId: '1:568613442085:ios:cdc6d3cdd5bcba8e54e5cc',
    messagingSenderId: '568613442085',
    projectId: 'task-sphere-e46ad',
    storageBucket: 'task-sphere-e46ad.firebasestorage.app',
    iosBundleId: 'com.example.tasksphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATQj7dXWQ0bdEKoz5kZ4Z0mnkiwKWB1Xw',
    appId: '1:568613442085:ios:cdc6d3cdd5bcba8e54e5cc',
    messagingSenderId: '568613442085',
    projectId: 'task-sphere-e46ad',
    storageBucket: 'task-sphere-e46ad.firebasestorage.app',
    iosBundleId: 'com.example.tasksphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0uzLJyIiNG3JCSF8J0M4LYPjd2FILMOo',
    appId: '1:568613442085:web:062af19219cc32df54e5cc',
    messagingSenderId: '568613442085',
    projectId: 'task-sphere-e46ad',
    authDomain: 'task-sphere-e46ad.firebaseapp.com',
    storageBucket: 'task-sphere-e46ad.firebasestorage.app',
  );
}
